name: Parse POC Request Issue

on:
  issues:
    types: [opened, edited]

jobs:
  parse_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'poc')
    steps:
      - name: Display Issue Information
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"

      - name: Parse POC Request Fields
        id: parse_fields
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"

          # Extract fields using sed for accuracy with multi-line handling
          LEAD_NAME=$(echo "$ISSUE_BODY" | sed -n '/What is the name of the lead or the customer?/{n;p;}')
          CUSTOMER_EMAIL=$(echo "$ISSUE_BODY" | sed -n '/What is the email of the customer\/lead/{n;p;}')
          CUSTOMER_TYPE=$(echo "$ISSUE_BODY" | sed -n '/Is it is a lead or an existing customer?/{n;p;}')
          POC_LINK=$(echo "$ISSUE_BODY" | sed -n '/preliminary POC/{n;p;}')
          API_SPEC=$(echo "$ISSUE_BODY" | sed -n '/Add the links to the customer/{n;p;}')
          DOCS_LINK=$(echo "$ISSUE_BODY" | sed -n '/API documentation online/{n;p;}')
          
          # Multi-line SDK languages - get all checked languages
          POC_LANGS=$(echo "$ISSUE_BODY" | sed -n '/SDK languages are POC required for?/,/Is an API Portal required too?/{/^\* \[x\]/{s/^\* \[x\] //;p;}}')

          # Display parsed values
          echo "Lead Name: $LEAD_NAME"
          echo "Customer Email: $CUSTOMER_EMAIL"
          echo "Customer Type: $CUSTOMER_TYPE"
          echo "Preliminary POC Link: $POC_LINK"
          echo "API Spec Link: $API_SPEC"
          echo "Documentation Link: $DOCS_LINK"
          echo "POC Required SDK Languages: $POC_LANGS"
