name: Parse POC Request Issue

on:
  issues:
    types: [opened, edited]

jobs:
  parse_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'poc')
    steps:
      - name: Display Issue Information
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"

      - name: Parse POC Request Fields
        id: parse_fields
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"

          # Remove markdown '**' symbols for bold text
          CLEAN_BODY=$(echo "$ISSUE_BODY" | sed 's/\*\*//g')

          # Use sed to capture the values after each markdown question
          LEAD_NAME=$(echo "$CLEAN_BODY" | sed -n '/What is the name of the lead or the customer\?/{n;p;}' | xargs)
          CUSTOMER_TYPE=$(echo "$CLEAN_BODY" | sed -n '/Is it is a lead or an existing customer\?/{n;p;}' | xargs)
          DOCS_LINK=$(echo "$CLEAN_BODY" | sed -n '/customer have existing API documentation online/{n;p;}' | xargs)
          SDK_LANGS=$(echo "$CLEAN_BODY" | sed -n '/SDK languages are POC required for\?/,/Is an API Portal required too\?/{/^\* \[x\]/{s/^\* \[x\] //;p;}}' | xargs -d '\n')
          POC_DEPTH=$(echo "$CLEAN_BODY" | sed -n '/expected depth of this proof-of-concept\?/,/Who is the AE/{/^\* \[x\]/{s/^\* \[x\] //;p;}}' | xargs)
          AE_NAME=$(echo "$CLEAN_BODY" | sed -n '/Who is the AE on this customer\//lead\?/{n;p;}' | xargs)
          DUE_DATE=$(echo "$CLEAN_BODY" | sed -n '/What date do you need this by\?/{n;p;}' | xargs)

          # Display parsed values
          echo "Lead Name: $LEAD_NAME"
          echo "Customer Type: $CUSTOMER_TYPE"
          echo "Documentation Link: $DOCS_LINK"
          echo "POC Required SDK Languages: $SDK_LANGS"
          echo "Expected Depth: $POC_DEPTH"
          echo "Account Executive Name: $AE_NAME"
          echo "Due Date: $DUE_DATE"
